# This is a generated file. Not intended for manual editing.
services:
  keycloak.auth.api:
    build:
      context: "C:\\Users\\v.shtackiy\\Downloads\\source-code-keycloak-dotnet\\after\\\
        keycloak-auth"
      dockerfile: "src/Keycloak.Auth.Api/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Keycloak.Auth.Api.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "keycloakauthapi:dev"
    ports: []
    volumes:
    - "C:\\Users\\v.shtackiy\\Downloads\\source-code-keycloak-dotnet\\after\\keycloak-auth\\\
      src\\Keycloak.Auth.Api:/app:rw"
    - "C:\\Users\\v.shtackiy\\Downloads\\source-code-keycloak-dotnet\\after\\keycloak-auth:/src:rw"
    - "C:\\Users\\v.shtackiy\\.nuget\\packages:/home/app/.nuget/packages"
    working_dir: "/app"
